# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 22:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20170814_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=120)),
                ('item_price', models.IntegerField(blank=True, max_length=120, null=True)),
                ('item_id', models.CharField(blank=True, max_length=120, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
    ]
